---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/dotmesh-io/dotscience-circleci-plugin

steps:
- name: build
  pull: default
  image: golang
  commands:
  - make install

- name: publish
  pull: default
  image: plugins/docker
  settings:
    auto_tag: true
    registry: quay.io
    repo: quay.io/dotmesh/dotscience-circleci-plugin
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

